services:
  dashboard:
    build: .
    container_name: studium-dashboard
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped